<?php
function rd_custom_post_types_register() {
  $post_types = [
    'service-areas' => [
      'supports' => [ 'title', 'revisions', 'editor', 'author', 'excerpt', 'thumbnail' ],
      'public' => true,
      'show_in_rest' => true,
      'has_archive' => false,
      'menu_position' => 5,
      'show_in_menu' => true,
      'menu_icon' => 'dashicons-networking',
      'rewrite' => [ 'slug' => 'movers', 'with_front' => false ],
      'labels' => [
        'name' => 'Service Areas',
        'singular_name' => 'Service Areas',
        'add_new' => 'Add New Service Areas',
        'add_new_item' => 'Add New Service Areas',
        'edit_item' => 'Edit Service Areas',
        'new_item' => 'New Service Areas',
        'view_item' => 'View Service Areas',
        'view_items' => 'View Service Areas',
        'search_items' => 'Search Service Areas',
        'not_found' => 'No Service Areas found',
        'not_found_in_trash' => 'No Service Areas found in trash',
        'parent_item_colon' => 'Parent Service Areas',
        'all_items' => 'All Service Areass',
        'archives' => 'Service Areas Archives',
        'attributes' => 'Service Areas Attributes',
        'insert_into_item' => 'Insert into Service Areas',
        'uploaded_to_this_item' => 'Uploaded to this Service Areas',
        'filter_items_list' => 'Filter Service Areass list',
        'items_list_navigation' => 'Service Areass list navigation',
        'items_list' => 'Service Areass list',
        'item_published' => 'Service Areas published',
        'item_published_privately' => 'Service Areas published privately',
        'item_reverted_to_draft' => 'Service Areas reverted to draft',
        'item_scheduled' => 'Service Areas scheduled',
        'item_updated' => 'Service Areas updated',
      ],
    ],
    'services' => [
      'supports' => [ 'title', 'revisions', 'editor', 'author', 'excerpt', 'thumbnail' ],
      'public' => true,
      'show_in_rest' => true,
      'has_archive' => false,
      'menu_position' => 5,
      'show_in_menu' => true,
      'menu_icon' => 'dashicons-clipboard',
      'rewrite' => [ 'slug' => 'services', 'with_front' => false ],
      'labels' => [
        'name' => 'Services',
        'singular_name' => 'Services',
        'add_new' => 'Add New Services',
        'add_new_item' => 'Add New Services',
        'edit_item' => 'Edit Services',
        'new_item' => 'New Services',
        'view_item' => 'View Services',
        'view_items' => 'View Servicess',
        'search_items' => 'Search Servicess',
        'not_found' => 'No Servicess found',
        'not_found_in_trash' => 'No Servicess found in trash',
        'parent_item_colon' => 'Parent Services',
        'all_items' => 'All Servicess',
        'archives' => 'Services Archives',
        'attributes' => 'Services Attributes',
        'insert_into_item' => 'Insert into Services',
        'uploaded_to_this_item' => 'Uploaded to this Services',
        'filter_items_list' => 'Filter Servicess list',
        'items_list_navigation' => 'Servicess list navigation',
        'items_list' => 'Servicess list',
        'item_published' => 'Services published',
        'item_published_privately' => 'Services published privately',
        'item_reverted_to_draft' => 'Services reverted to draft',
        'item_scheduled' => 'Services scheduled',
        'item_updated' => 'Services updated',
      ],
    ],
  ];

  foreach ( $post_types as $key => $post_type ) {
    register_post_type($key, $post_type);
  }
}

add_action( 'init', 'rd_custom_post_types_register', 0 );